# Generated by Django 3.1.4 on 2021-02-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20201117_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='unidae',
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria', verbose_name='categoria'),
        ),
    ]
